create table BOARD (
	BOARD NUMBER PRIMARY KEY,
	USERID VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	HITCOUNT NUMBER DEFAULT 0,
	REGDATE DATE DEFAULT SYSDATE,
	CONSTRAINT BOARD_FK FOREIGN KEY(USERID)
	REFERENCES MEMBERS(USERID)
)

CREATE SEQUENCE BOARDSEQ

select * from members